# -*- coding: utf-8 -*-
"""Bus Ticket Booking System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQVCNT3y1hLkrOSlSl97zukPtWffLZXO

Bus Ticket Booking System
"""

buses = {
    1: {
        "name": "Delhi - Jaipur Express",
        "source": "Delhi",
        "destination": "Jaipur",
        "time": "08:00 AM",
        "price": 500,
        "seats": 20
    },
    2: {
        "name": "Delhi - Agra Express",
        "source": "Delhi",
        "destination": "Agra",
        "time": "10:00 AM",
        "price": 350,
        "seats": 15
    },
    3: {
        "name": "Delhi - Lucknow Express",
        "source": "Delhi",
        "destination": "Lucknow",
        "time": "07:30 PM",
        "price": 800,
        "seats": 25
    },
    4: {
        "name": "Jaipur - Delhi Express",
        "source": "Jaipur",
        "destination": "Delhi",
        "time": "06:00 PM",
        "price": 500,
        "seats": 18
    }
}

bookings = []

"""Display Buses"""

def display_buses():
    print("\n" + "=" * 80)
    print("                         AVAILABLE BUSES")
    print("=" * 80)

    print(f"{'ID':<5}{'Bus Name':<28}{'Route':<25}{'Time':<12}{'Price':<10}{'Seats'}")
    print("-" * 80)

    for bus_id, bus in buses.items():
        route = bus["source"] + " -> " + bus["destination"]

        print(
            f"{bus_id:<5}"
            f"{bus['name']:<28}"
            f"{route:<25}"
            f"{bus['time']:<12}"
            f"Rs.{bus['price']:<6}"
            f"{bus['seats']}"
        )

    print("=" * 80)

"""Book Ticket"""

def book_ticket():

    display_buses()

    try:
        bus_id = int(input("\nEnter Bus ID: "))

        if bus_id not in buses:
            print("Invalid Bus ID.")
            return

        bus = buses[bus_id]

        if bus["seats"] <= 0:
            print("Sorry, no seats available.")
            return

        name = input("Enter passenger name: ")
        age = int(input("Enter passenger age: "))
        phone = input("Enter phone number: ")

        seats = int(input("Enter number of seats: "))

        if seats <= 0:
            print("Invalid number of seats.")
            return

        if seats > bus["seats"]:
            print(f"Only {bus['seats']} seats are available.")
            return

        total = seats * bus["price"]

        booking_id = len(bookings) + 1

        booking = {
            "booking_id": booking_id,
            "passenger": name,
            "age": age,
            "phone": phone,
            "bus_id": bus_id,
            "bus_name": bus["name"],
            "source": bus["source"],
            "destination": bus["destination"],
            "time": bus["time"],
            "seats": seats,
            "total": total
        }

        bookings.append(booking)

        bus["seats"] -= seats

        print("\n" + "=" * 50)
        print("             TICKET BOOKED SUCCESSFULLY")
        print("=" * 50)

        print("Booking ID :", booking_id)
        print("Passenger  :", name)
        print("Age        :", age)
        print("Phone      :", phone)
        print("Bus        :", bus["name"])
        print("Route      :", bus["source"], "->", bus["destination"])
        print("Time       :", bus["time"])
        print("Seats      :", seats)
        print("Total      : Rs.", total)

        print("=" * 50)

    except ValueError:
        print("Please enter valid information.")

"""View Booking

"""

def view_bookings():

    if len(bookings) == 0:
        print("\nNo bookings found.")
        return

    print("\n" + "=" * 90)
    print("                         ALL BOOKINGS")
    print("=" * 90)

    for booking in bookings:

        print("\nBooking ID :", booking["booking_id"])
        print("Passenger  :", booking["passenger"])
        print("Age        :", booking["age"])
        print("Phone      :", booking["phone"])
        print("Bus        :", booking["bus_name"])
        print("Route      :", booking["source"], "->", booking["destination"])
        print("Time       :", booking["time"])
        print("Seats      :", booking["seats"])
        print("Total      : Rs.", booking["total"])

        print("-" * 90)

"""Search Booking"""

def search_booking():

    try:
        booking_id = int(input("\nEnter Booking ID: "))

        for booking in bookings:

            if booking["booking_id"] == booking_id:

                print("\n" + "=" * 50)
                print("                 BOOKING DETAILS")
                print("=" * 50)

                print("Booking ID :", booking["booking_id"])
                print("Passenger  :", booking["passenger"])
                print("Age        :", booking["age"])
                print("Phone      :", booking["phone"])
                print("Bus        :", booking["bus_name"])
                print("Route      :", booking["source"], "->", booking["destination"])
                print("Time       :", booking["time"])
                print("Seats      :", booking["seats"])
                print("Total      : Rs.", booking["total"])

                print("=" * 50)

                return

        print("Booking not found.")

    except ValueError:
        print("Invalid Booking ID.")

"""Cancel Bookking"""

def cancel_booking():

    try:
        booking_id = int(input("\nEnter Booking ID to cancel: "))

        for booking in bookings:

            if booking["booking_id"] == booking_id:

                bus_id = booking["bus_id"]

                # Return seats to bus
                buses[bus_id]["seats"] += booking["seats"]

                bookings.remove(booking)

                print("\nBooking cancelled successfully.")
                print("Refund amount: Rs.", booking["total"])

                return

        print("Booking not found.")

    except ValueError:
        print("Invalid Booking ID.")

"""Main Menu"""

def main():

    while True:

        print("\n")
        print("=" * 50)
        print("          BUS TICKET BOOKING SYSTEM")
        print("=" * 50)

        print("1. View Available Buses")
        print("2. Book Ticket")
        print("3. View All Bookings")
        print("4. Search Booking")
        print("5. Cancel Booking")
        print("6. Exit")

        print("=" * 50)

        choice = input("Enter your choice: ")

        if choice == "1":
            display_buses()

        elif choice == "2":
            book_ticket()

        elif choice == "3":
            view_bookings()

        elif choice == "4":
            search_booking()

        elif choice == "5":
            cancel_booking()

        elif choice == "6":
            print("\nThank you for using Bus Ticket Booking System.")
            break

        else:
            print("\nInvalid choice. Please try again.")

main()

